### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by tkd-hgoertz** [colinmollenhour/Cm_RedisSession#124] opened 2017-09-28 13:13 UTC
With php-redis-session-abstract 1.3.5 and credis 1.9.0
we run into php fatal error because of
```
Class Cm_RedisSession_Model_Session_Config contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Cm\RedisSession\Handler\ConfigInterface::getSentinelServers, Cm\RedisSession\Handler\ConfigInterface::getSentinelMaster, Cm\RedisSession\Handler\ConfigInterface::getSentinelVerifyMaster, ...) in /var/www/htdocs/.../app/code/Cm/RedisSession/Model/Session/Config.php on line 195
```

**Comment by colinmollenhour** [comment] 2017-09-29 02:24
Thanks for the report, but duplicate of #123

**Closed by colinmollenhour** 2017-09-29 02:24 UTC

**Comment by tkd-hgoertz** [comment] 2017-09-29 07:19
thx, sorry didn't recognized the duplicate
