### ISSUE TITLE
Seems unusable (ಥ﹏ಥ)

### ISSUE THREAD

**Issue by rakeev** [colinmollenhour/Cm_RedisSession#108] opened 2017-03-21 14:30 UTC
1. Local codepool in modman and community one in Cm_RedisSession.xml - no rewrite actually happens
2. Wrong (inversed) handling of disable_locking and no locking by default

**Comment by colinmollenhour** [comment] 2017-03-22 16:24
Yeah unfortunately Magento crew put the bundled version in community instead of core causing the standalone one to either have to replace core files or break from using community like it was first and use local codepool.. It is very hackish, but basically the autoloader will still pick up the class file from local instead of community, but then the XML file will be loaded from community so now it depends on a Magento core that includes the bundled version... I suppose I could change the github version to use local codepool in the module XML which should fix old versions of Magento.. Just not sure if there will be unintended consequences after doing that..

Pushed a fix for the disable_locking regression. Thanks!

**Closed** 2017-07-13 12:27 UTC
