### ISSUE TITLE
Redis::expire() expects parameter 2 to be integer, string given

### ISSUE THREAD

**Issue by seansan** [colinmollenhour/Cm_RedisSession#132] opened 2017-11-30 11:32 UTC
I upgraded to last version recently. Seeing this in logging. 
Using magento github lts 1937

`Redis::expire() expects parameter 2 to be integer, string given  in /app/code/local/Credis/Client.php on line 1132`

**Comment by kanevbg** [comment] 2017-12-05 13:42
With the standard version bundled with Magento 1.9.3.1 I found these in system.log:

2017-12-04T07:16:53+00:00 ERR (3): Warning: Redis::expire() expects parameter 2 to be long, string given  in public_html/lib/Credis/Client.php on line 931

**Comment by kanevbg** [comment] 2017-12-08 09:48
May this be causing session drops or data dropping in general? It is not persistent issue, when it appears it is for about 1-2 seconds in the log. Any ideas what may be the case?

**Comment by seansan** [comment] 2017-12-08 09:51
​We have the same: and we see sometimes admins suddenly logged ​out in
backend

**Comment by kanevbg** [comment] 2017-12-08 09:55
Just remembered that yesterday I suddenly lost my session from the frontend but when I checked there was no recent log of this warning

**Comment by seansan** [comment] 2017-12-08 11:14
Do we know where the call to expire() is coming from?

**Comment by seansan** [comment] 2017-12-11 18:58
@colinmollenhour is there a smart way to debug this? (our log is almost 99% this error line) - also frequent log outs when in cache screen in admin html

**Comment by colinmollenhour** [comment] 2017-12-11 19:27
My guess is that the phpredis extension changed a loose type to a strict one. I'll push a fix.

**Comment by seansan** [comment] 2017-12-11 19:35
​muy gracias ;) - I can download and test it​

**Comment by seansan** [comment] 2017-12-12 10:15
​Can this ​be related? + also call
https://github.com/colinmollenhour/Cm_RedisSession/issues/140

Maybe if session is lost due to this: then it starts a new one: resulting
in concurrent error

Idem for below?

[12-Dec-2017 10:10:00] WARNING: [pool] child 26880 said into stderr:
"NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 805306368
bytes exhausted (tried to allocate 20480 bytes) in
app/code/local/Credis/Client.php on line 538"

**Comment by colinmollenhour** [comment] 2017-12-12 15:39
Did the pushed commit fix the warnings regarding `expire()`?

If a fatal error occurs then the lock is not released so all subsequent requests for the same session id will block waiting for the lock and when the number of these waiting requests exceeds the configuration threshold then you will see the ConcurrentConnectionException. However, the root of the issue is the fatal errors, not the concurrent connections message. The locking mechanism does not attempt to account for frequent fatal errors (although it does occasionally do "zombie" cleanup which can only work decently well on a single-node system).

Requiring more than 800MB for a page load means something is seriously wrong.. Most page loads should take no more than about 32MB in my experience. What is at the indicated line number in Credis_Client on your version?

**Comment by seansan** [comment] 2017-12-12 17:11
applied fix. Yes I know about the mem usage. Trust me this was never an issue until now. So let's hope this is the fix that fixes all ;)

**Comment by seansan** [comment] 2017-12-12 17:14
Hi Colin - where is the fix? https://github.com/colinmollenhour/Cm_RedisSession/commits/master
I updated but still seeing error. Am I missing something?

**Comment by seansan** [comment] 2017-12-12 17:49
error still here. 2017-12-12T17:35:55+00:00 ERR (3): Warning: Redis::expire() expects parameter 2 to be integer, string given  in /app/code/local/Credis/Client.php on line 1132

Credis/Client.php on line 1132

**Comment by seansan** [comment] 2017-12-13 15:49
@colinmollenhour how are u? Was wondering if you had some time to check. mem usage errors piling up. And never seen that before since upgrade. If I can help then let me know

**Comment by colinmollenhour** [comment] 2017-12-13 21:06
The fix is in the other repo: https://github.com/colinmollenhour/php-redis-session-abstract/commit/4671d63212fe05802f21d2fe3086f3425900483e

So if you're using composer you need to `composer update` it.

**Comment by seansan** [comment] 2017-12-14 09:34
​ah ok. What is the difference betw the 2?​


On Wed, Dec 13, 2017 at 10:06 PM, Colin Mollenhour <notifications@github.com

**Comment by seansan** [comment] 2017-12-14 09:38
​I just checked our own local code. seems the fix was already there?

File: app/code/local/Cm/RedisSession/lib/src/Cm/RedisSession/Handler.php

So my conclusion would then be the error is still there?

[image: Inline image 1]​

**Comment by seansan** [comment] 2017-12-14 14:07
This is where "our" problem comes from

![image](https://user-images.githubusercontent.com/652395/33996094-664db474-e0e0-11e7-870f-33fa717de4c3.png)

**Comment by colinmollenhour** [comment] 2017-12-14 17:40
As a temporary workaround you could either install an older version of phpredis or just use the standalone mode since this seems to be specific to phpredis. Personally I think phpredis is too buggy and has too many BC breaking changes like this to be worthwhile and prefer to use standalone mode.

Since you are able to produce the issue please use a debugger to pause execution just before the expire call and see where the string is coming from.

**Comment by seansan** [comment] 2017-12-14 18:13
​hmm no debugger here ​: but will find time to check it out further

how do I switch to standalone mode? (and disable phpredis)

**Comment by seansan** [comment] 2017-12-14 18:27
​Sorry too fast ... found ;)

>> how do I switch to standalone mode? (and disable phpredis)
<force_standalone>1</force_standalone>  
​

**Comment by seansan** [comment] 2018-03-23 10:38
@colinmollenhour sorry to bring this up again - but we quite liked the speed of phpredis

Can we move back to phpredis you think? (and try again) 
And what library do we need to pull from for the expire fix?
https://github.com/colinmollenhour/Cm_RedisSession/issues/132#issuecomment-351720123

**Comment by seansan** [comment] 2018-03-30 07:05
@colinmollenhour we downloaded redissession and Magento Github LTS 1938: I am still seeing 

Warning: Redis::expire() expects parameter 2 to be integer, string given  in /app/code/local/Credis/Client.php on line 1132

Did you or someone find a solution for this? thanks!

**Comment by colinmollenhour** [comment] 2018-03-30 14:18
Please log a backtrace, that should make the location of the issue obvious.

**Comment by seansan** [comment] 2018-05-14 09:56
@kanevbg are you still having this issue?

**Comment by adioe3** [comment] 2018-07-23 14:13
This is caused by cache lifetimes being set via layout XML, for example in this block:

```
<block type="cms/block" name="cms_sidebar_flexible_shipping" after="-">
    <action method="setCacheLifetime"><lifetime>false</lifetime></action>
</block>
```

The `<lifetime>` value `false` gets interpreted as a string and then in `\Zend_Cache_Backend::getLifetime()` the check

```
if ($specificLifetime === false) {
    return $this->_directives['lifetime'];
}
```

fails. My solution was to rewrite this class and extend it so:

```
protected function _getAutoExpiringLifetime($lifetime, $id)
{
    if ($lifetime === 'false') {
        $lifetime = false;
    }
    return parent::_getAutoExpiringLifetime($lifetime, $id);
}
```

No more warnings or problems.

**Comment by colinmollenhour** [comment] 2018-07-23 21:16
Great find! I still don't understand why the cast operator doesn't cast "false" to some integer (probably 0) and throw a PHP warning, though..

**Comment by seansan** [comment] 2018-07-24 06:31
I have applied the fix and can confirm this works.

[image: image.png]

**Comment by colinmollenhour** [comment] 2018-07-26 01:35
Great, please provide a PR! Thanks!

**Comment by seansan** [comment] 2018-07-26 07:01
​​
Correction. Still not the fix for me (applied shared fix but still see in
loggign)

Warning: Redis::expire() expects parameter 2 to be integer, string given
in /var/www/html/shirts/public_html/app/code/local/Credis/Client.php on
line 1142

**Comment by adioe3** [comment] 2018-07-26 09:34
@colinmollenhour the check in the Zend method uses an identity check which checks for type so it doesn't perform any casting.

**Comment by rafaelpatro** [comment] 2018-07-31 23:40
@adioe3
Did you try json?

```xml
<action method="setCacheLifetime" json="lifetime"><lifetime>false</lifetime></action>
```
Reference: http://fbrnc.net/blog/2015/06/cache-and-layout-xml-tricks

**Comment by seansan** [comment] 2018-10-16 18:34
I can confirm this is still an error. Although strangely enough a _lot less often_

`2018-10-16T01:18:10+00:00 ERR (3): Warning: Redis::expire() expects parameter 2 to be integer, string given  in app/code/local/Credis/Client.php on line 1142

Has anyone found the final fix?


`

**Comment by seansan** [comment] 2018-12-15 09:45
Which module? Might be the same

**Comment by kanevbg** [comment] 2018-12-15 10:06
Lesti FPC

**Comment by kanevbg** [comment] 2018-12-20 22:03
@seansan Did you found anything?

**Comment by seansan** [comment] 2018-12-21 06:54
Don’t use lesti but mirasvit version
Thx

**Closed** 2019-02-18 18:59 UTC
